config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 6}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles, dependent: :destroy
    validates :username, presence: true, 
                         uniqueness: {case_sensitive: false}, 
                         length: {minimum: 3, maximum: 45}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                         uniqueness: {case_sensitive: false}, 
                         length: {maximum: 105},
                         format: {with: VALID_EMAIL_REGEX}
    has_secure_password
    # rubular.com
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be loged in to perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        # @article = Article.find(params[:id])
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 2)
    end

    def new
        @article = Article.new
    end

    def edit
        # @article = Article.find(params[:id])
    end

    def update
        # @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to articles_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def create
        debugger
        # flash[:notice] = "ok"
        # render plain: params[:article]
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            redirect_to @article
            flash[:notice] = "Article was created successfully."
        else
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        # @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

    private 
    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title,:description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "you can only edit or delete your article"
            redirect_to @article
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

    def index
        @categories = Category.paginate(page: params[:page], per_page: 2)
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render :new , status: :unprocessable_entity
        end
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 2)

    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category name updated successfully"
            redirect_to @category
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform that action"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end

    def about
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password_digest])
            session[:user_id] = user.id
            flash[:notice] = "Logged is successfully"
            redirect_to user
        else
            flash.now[:alert] = "There was something wrong with your login details"
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id] =  nil
        flash[:notice] = "Logged out"
        redirect_to root_path, status: :see_other
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 2)
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 2)
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have succesfully signed up."
            redirect_to articles_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated articles successfully deleted."
        redirect_to articles_path, status: :see_other
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated."
            redirect_to @user
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        unless current_user.admin?
            flash[:alert] = "You can only edit or delete your own account"
            redirect_to @user
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block" )
    end


    
end

app/views/articles/_article.html.erb
<div class="container">
        
<div class="container">
        <% @articles.each do |article| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                        <%# by <%= article.user.username if article.user %>
                        <% if article.user %>
                            by <%= link_to article.user.username, user_path(article.user) %>
                        <% end %>
                        <% if article.categories.any? %>
                            <div class="mt-2"><%= render article.categories %></div>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
                        <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                            <%= link_to "View", article, class:"btn btn-outline-success" %>
                            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                                <%= link_to "Edit", edit_article_path(article), class:"btn btn-outline-info" %>
                                <%= link_to "Delete",article_path(article), data:{turbo_method: :delete,turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
                            <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
        <% end %>

        

    </div>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @article %>
            <%= form_with(model: @article,class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :title, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title for article" %>
                    </div>
                </div>
                    
                <div class="form-group row">
                    <%= f.label :description, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_area :description, rows: 10 , class: "form-control shadow rounded", placeholder: "Description of article" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= f.label :category, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.collection_select(:category_ids,Category.all,:id,:name,
                        {prompt: "Make your selection from the list below (can be empty)"},
                        {multiple: true, size: 3, class: "custom-select shadow rounded"}) %>
                    </div>
                </div>

                <div class="form-group row justify-content-center">
                    <%= f.submit  class: "btn btn-outline-light btn-lg"%>
                </div>
            <% end %>
        </div>
        <div class="mb-3"></div>
        <%= link_to '[ Cancel and return to article listing ]', articles_path, class: "text-info" %>
    </div>
</div>
        
    

app/views/articles/edit.html.erb
    <h1 class="mt-4 text-center">Edit Article</h1>
    <%= render 'form' %>

app/views/articles/index.html.erb
    <h1 class="text-center mt-4">Listing all articles</h1>
    
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

    <%= render 'article' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
    <h1 class="text-center mt-4">Create New Article</h1>
    <%= render 'form' %>

app/views/articles/show.html.erb
    <h1 class="text-center mt-4"><%= @article.title %></h1>

    <div class="container">
        
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                        by <%= @article.user.username %>
                        <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
                        <% if @article.categories.any? %>
                            <div class="mt-2"><%= render @article.categories %></div>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <div class="card-text text-left"><%= simple_format(@article.description) %></div>
                        <% if logged_in? && (@article.user == current_user  || current_user.admin?) %>
                            <%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-info" %>
                            <%= link_to "Delete",article_path(@article), data:{turbo_method: :delete,turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors' , obj: @category %>
            <%= form_with(model: @category,class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :name,"Category name", class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a category name" %>
                    </div>
                </div>
                    

                <div class="form-group row justify-content-center">
                    <%= f.submit  class: "btn btn-outline-light btn-lg"%>
                </div>
            <% end %>
        </div>
        <div class="mb-3"></div>
        <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-info" %>
    </div>
</div>
        
    

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category</h1>
<%= render 'form'  %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories list</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
        
<div class="container">
        <% @categories.each do |category| %>
        <div class="row justify-content-md-center">
            <div class="col-4 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
                        <p class="card-text"><%= pluralize(category.articles.count, 'articles') %></p>
                            
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(category.created_at) %> ago, edited <%= time_ago_in_words(category.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create new category</h1>
<%= render 'form'  %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<div class="text-center mt-4">
    <% if logged_in? and current_user.admin? %>
        <%= link_to "Edit category name",  edit_category_path(@category), class:"btn btn-outline-info" %>
    <% end %>
</div>

<h1 class="text-center mt-4">Articles</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name,msg| %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <h4 ><%= msg %></h4>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Alpha-Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
  
      <li class="nav-item">
        <%= link_to 'Article List', articles_path, class: "nav-link" %>
      </li>

      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "New Category", new_category_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View Categories", categories_path, class: "dropdown-item" %>
          </div>
      </li>

      
      <% if logged_in? %>

        <li class="nav-item">
          <%= link_to 'New Articles', new_article_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            <%= "Admin" if current_user.admin? %> Profile [ <%= current_user.username %> ]
          </a>
          <div class="dropdown-menu">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", data: {turbo_method: :delete, turbo_confirm: "Your are article also gonna be deleted "} %>
          </div>
        </li>

        <li class="nav-item">
          <%= link_to "Log out", logout_path, class: "nav-link", data: { turbo_method: :delete} %> 
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Signup", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">

    <%# navbar start %>
      <%= render 'layouts/navigation' %>
    <%# navbar end %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>

    
    
  </body>
  

</html>

app/views/pages/about.html.erb
<h1>about page</h1>

app/views/pages/home.html.erb
    <div class="container" id="home-container">
        <div class="jumbotron text-center text-white">
            <h1 class="display-4">Hello, world!</h1>
            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
            <p class="lead">
                <%= link_to "Sign Up!", signup_path, class: "btn btn-success btn-lg" %>
            </p>
        </div>
    </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors' , obj: @user %>
            <%= form_with(model: @user,class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :username, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
                    </div>
                </div>
                    
                <div class="form-group row">
                    <%= f.label :email, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.email_field :email,  class: "form-control shadow rounded", placeholder: "Enter a email" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= f.label :password, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.password_field :password,  class: "form-control shadow rounded", placeholder: "Enter a password" %>
                    </div>
                </div>

                <div class="form-group row justify-content-center">
                    <%= f.submit(@user.new_record? ? "Sign Up" : "Update account",  class: "btn btn-outline-light btn-lg")%>
                </div>
            <% end %>
        </div>
        <div class="mb-3"></div>
        <%= link_to '[ Cancel and return to article listing ]', articles_path, class: "text-info" %>
    </div>
</div>
        
    

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form'  %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<div class="container">
        <% @users.each do |user| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                        by <%= link_to user.username, user, class: "text-success"  %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to gravatar_for(user, size: 150), user %></h5>
                        <p class="card-text"><%= pluralize(user.articles.count, 'article') %></p>
                        <%= link_to "View Profile", user, class:"btn btn-outline-success" %>
                            <% if logged_in? %>
                                <% if user == current_user %>
                                    <%= link_to "Edit Profile", edit_user_path(user), class:"btn btn-outline-info" %>
                                <% end %>
                                <% if current_user.admin? %>
                                    <%= link_to "Delete Profile", user_path(user), class: "btn btn-outline-danger", data: {turbo_method: :delete, turbo_confirm: "Are You sure"} %>
                                <% end %>
                            <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Signup</h1>
<%= render 'form'  %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200%>

<div class="text-center mt-4">
    <% if logged_in? and @user == current_user %>
        <%= link_to "Edit your profile",  edit_user_path(@user), class:"btn btn-outline-info" %>
    <% end %>
</div>

<h1 class="text-center mt-4">Articles</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>